### ISSUE TITLE
Audio volume level is too low at recording

### ISSUE THREAD

**Issue by Wildernesss** [carsonsaldanha/screen-recorder#30]
Hi,

Thanks for this nice application that I'd like to use instead of [Chrome Screen Recorder](https://chrome.google.com/webstore/detail/screen-recorder/hniebljpgcogalllopnjokppmgbhaden) extension that will soon be no more available with the end of Chrome extensions.

But for the moment I cannot use it because the recorder sound volume is to low when playing back the recorded video. The recorded sound volume level is too low so that you need to increase it on speaker or headphone to have the same level to play back the video and hear the original sound. Or boost the sound volume level with a tool. That is not the case with Chrome Screen Recorder.

The video volume level should be at output the same as at input.

Thanks a lot for your nice apps and all your work!

Laurent

**Comment by carsonsaldanha** [comment]
Hi! Thank you for your post! Are you on ChromeOS? It's not extensions that they're shutting down, it's Chrome Apps. I'm pretty sure that Screen Recorder extension will still work when that happens.

As for the volume level, it seems that the Screen Recorder web API has a pretty low bitrate for audio. I've also noticed that if you record internal audio, it oftentimes sounds very canned and static-ky on the recording.

Now that the built-in screen recorder for ChromeOS has gotten so good and supports recording internal audio and microphone at much better quality, I've not looked at this project in some time. I think the only advantage mine has is the ability to record a single tab or application and not have other things covering it appear in the recording.

I'll try looking if there's a way to increase bitrate, but I'm not sure if it's possible. 🙁
